"""empty message

Revision ID: 571afa787ec1
Revises: None
Create Date: 2013-10-08 12:16:07.687000

"""

# revision identifiers, used by Alembic.
revision = '571afa787ec1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
